In [1]:
import numpy as np

In [16]:
A = np.array([[6.59,   1.28,   0.79,  1.195, -0.21  ], 
              [0.92,   3.83,    1.3,  -1.63,  1.02  ],
              [1.15,  -2.46,   5.77,    2.1,  1.483 ],
              [1.285,  0.16,    2.1,   5.77,  -18   ],
              [0.69,  -1.68, -1.217,      9,   -6   ] ], dtype = float)
B = np.array([2.1, 0.36, 3.89, 11.04, -0.27]) 
eps = 0.000000001

In [19]:
np.linalg.solve(A,B)

array([-0.04709818,  0.38731978,  0.51350467,  1.23504243, -0.15744419])

In [3]:
def check_diag_more(a):
    r = []
    for i in range(0,a.shape[0]):
        s = []
        for j in range(0, a.shape[1]):
            if i == j:
                s.append(0)
            else:
                s.append(abs(a[i,j]))
        r.append(sum(s))
    r = np.array(r)
    for i in range(0,len(r)):
        if abs(np.diag(a)[i]) >= r[i]:
            print(True)
        else:
            print(False)

In [4]:
check_diag_more(A)

True
False
False
False
False


In [18]:
A = np.array([[6.59,   1.28,   0.79,  1.195, -0.21  ], 
              [0.92,   4.93,    1.3,  -1.63,  1.02  ],
              [2.07,  1.37,   7.07,    0.47,  2.503 ],
              [-0.145,  -1.74,    -2.1,   6.57,  1.58  ],
              [1.285,  0.16,    2.1,   5.77,  -18   ] ], dtype = float)
B = np.array([2.1, 0.36, 4.25,6.12, 11.04]) 

In [6]:
check_diag_more(A)

True
True
True
True
True


In [7]:
np.linalg.solve(A,B)

array([-0.04709818,  0.38731978,  0.51350467,  1.23504243, -0.15744419])

In [8]:
def s(a):
    d = []
    for i in range(0,a.shape[0]):
        v = []
        for j in range(0, a.shape[1]):
            if i == j:
                v.append(0)
            else:
                v.append(a[i,j]*x[j])
        d.append(sum(v))
    return d 

In [20]:
x = np.zeros(5)
res = []
counter =0
error = 2
while error>eps:
    for i in range(0,len(x)):
        x[i] = (1/A[i,i]) * (B[i] - s(A)[i])
    res.append(x.copy())
    if counter>=1:
        #print(res[counter]-res[counter-1])
        error = abs(res[counter]-res[counter-1]).max()
    counter = counter +1
    print('COUNTER: ',counter,x)

COUNTER:  1 [ 0.31866464  0.01355548  0.50520413  1.10361059 -0.17775474]
COUNTER:  2 [ 0.04968051  0.33219547  0.51177888  1.22691201 -0.15383285]
COUNTER:  3 [-0.03459488  0.38200625  0.51013548  1.23196576 -0.15797814]
COUNTER:  4 [-0.04512132  0.38693253  0.51339448  1.23507669 -0.15730838]
COUNTER:  5 [-0.04701164  0.38731591  0.51342972  1.2349867  -0.15746465]
COUNTER:  6 [-0.04707899  0.38732177  0.51350961  1.23504989 -0.15743983]
COUNTER:  7 [-0.04710037  0.38732044  0.51350314  1.23504103 -0.15744497]
COUNTER:  8 [-0.04709789  0.38731982  0.51350494  1.23504273 -0.15744404]
COUNTER:  9 [-0.04709827  0.38731979  0.51350462  1.23504238 -0.15744421]
COUNTER:  10 [-0.04709817  0.38731978  0.51350468  1.23504244 -0.15744418]
COUNTER:  11 [-0.04709818  0.38731978  0.51350466  1.23504243 -0.15744419]
COUNTER:  12 [-0.04709818  0.38731978  0.51350467  1.23504243 -0.15744419]
COUNTER:  13 [-0.04709818  0.38731978  0.51350467  1.23504243 -0.15744419]


In [21]:
np.dot(A,x)-B

array([-7.07512715e-10, -7.06673609e-11, -7.35058237e-10, -3.42915030e-10,
        0.00000000e+00])