In [29]:
import numpy as np

In [33]:
A = np.array([[3.81, 0.25, 1.28, 1.75],
              [2.25, 1.32, 5.58, 0.49],
              [5.31, 7.28, 0.98, 1.04],
              [10.39, 2.45, 3.35, 2.28]])

b = np.array([4.21, 7.47, 2.38, 11.48])
print(np.linalg.solve(A,b))
def check_diag_more(a):
    r = []
    for i in range(0,a.shape[0]):
        s = []
        for j in range(0, a.shape[1]):
            if i == j:
                s.append(0)
            else:
                s.append(abs(a[i,j]))
        r.append(sum(s))
    r = np.array(r)
    for i in range(0,len(r)):
        if abs(np.diag(a)[i]) >= r[i]:
            print(True)
        else:
            print(False)
            
            

[ 0.94107373 -0.45285249  1.1000052  -0.38301968]
False
False
False
False
(4, 4)


array([ 0.94107373, -0.45285249,  1.1000052 , -0.38301968])

In [31]:
check_diag_more(A)
np.linalg.solve(A,B)

True
False
False
False


NameError: name 'B' is not defined

In [71]:
def mzeros(matrix, i):
    for j in range(i+1, 4):
        k = matrix[j, i]/matrix[i, i]
        A_i = matrix[i, i:]
        A_j = matrix[j, i:]
        matrix[j, i:] = A_j - k*A_i
    return matrix

In [4]:
A.dot(A.T)

array([[ 19.2795,  16.9024,  25.1255,  48.4764],
       [ 16.9024,  38.1814,  27.5351,  46.4217],
       [ 25.1255,  27.5351,  83.2365,  78.6611],
       [ 48.4764,  46.4217,  78.6611, 130.3755]])

In [72]:
for i in range(4):
    m, s = np.unravel_index(matrix[i:4, i:4].argmax(), matrix[i:4, i:4].shape) #get max(ind)
    m, s = m+i, s+i  #real ind(whole matr),not submatr
    matrix[:, [i, s]] = matrix[:, [s, i]] #swap max and i-th elem
    matrix[[i, m], :] = matrix[[m, i], :] #swap rows(max and i-th)
    matrix = mzeros(matrix, i)#zeros under (i,i) elem
    print(np.round(matrix,3))
print(np.round(matrix,3))

[[ 1.039e+01  2.450e+00  3.350e+00  2.280e+00  1.148e+01]
 [ 0.000e+00  7.890e-01  4.855e+00 -4.000e-03  4.984e+00]
 [ 0.000e+00  6.028e+00 -7.320e-01 -1.250e-01 -3.487e+00]
 [ 0.000e+00 -6.480e-01  5.200e-02  9.140e-01  0.000e+00]
 [ 0.000e+00  1.000e+00  2.000e+00  3.000e+00  4.000e+00]]
[[10.39   2.45   3.35   2.28  11.48 ]
 [ 0.     6.028 -0.732 -0.125 -3.487]
 [ 0.    -0.     4.95   0.013  5.441]
 [ 0.     0.    -0.027  0.9   -0.375]
 [ 0.     1.     2.     3.     4.   ]]
[[10.39   2.45   3.35   2.28  11.48 ]
 [ 0.     6.028 -0.732 -0.125 -3.487]
 [ 0.    -0.     4.95   0.013  5.441]
 [ 0.     0.     0.     0.901 -0.345]
 [ 0.     1.     2.     3.     4.   ]]
[[10.39   2.45   3.35   2.28  11.48 ]
 [ 0.     6.028 -0.732 -0.125 -3.487]
 [ 0.    -0.     4.95   0.013  5.441]
 [ 0.     0.     0.     0.901 -0.345]
 [ 0.     1.     2.     3.     4.   ]]
[[10.39   2.45   3.35   2.28  11.48 ]
 [ 0.     6.028 -0.732 -0.125 -3.487]
 [ 0.    -0.     4.95   0.013  5.441]
 [ 0.     0.     0.   

In [73]:
diagonalized_matrix = matrix[:4,:5]
permuted_index_columns = list(matrix[4,:].astype(np.int32))
print(diagonalized_matrix)
res = []
for i in reversed(range(4)):
    x = diagonalized_matrix[i,4]/diagonalized_matrix[i,i]
    coef = diagonalized_matrix[i,(i+1):4]
    for j,solution in enumerate(reversed(res)):
        x-=(solution*coef[j])/diagonalized_matrix[i,i]
    res.append(x)
res = res[::-1]
res
print(diagonalized_matrix)

[[ 1.03900000e+01  2.45000000e+00  3.35000000e+00  2.28000000e+00
   1.14800000e+01]
 [ 0.00000000e+00  6.02788258e+00 -7.32078922e-01 -1.25235804e-01
  -3.48706449e+00]
 [ 0.00000000e+00 -1.11022302e-16  4.95041956e+00  1.26575251e-02
   5.44063920e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  9.00524911e-01
  -3.44918767e-01]]
[[ 1.03900000e+01  2.45000000e+00  3.35000000e+00  2.28000000e+00
   1.14800000e+01]
 [ 0.00000000e+00  6.02788258e+00 -7.32078922e-01 -1.25235804e-01
  -3.48706449e+00]
 [ 0.00000000e+00 -1.11022302e-16  4.95041956e+00  1.26575251e-02
   5.44063920e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  9.00524911e-01
  -3.44918767e-01]]


In [84]:
g =np.linalg.solve(A,b.T)
g

array([[ 0.94107373],
       [-0.45285249],
       [ 1.1000052 ],
       [-0.38301968]])

In [75]:
solution_matrix = np.reshape(np.array(res),(1,4))
print(solution_matrix.dot(A.T))
print(b)

[[ 4.21  7.47  2.38 11.48]]
[[ 4.21  7.47  2.38 11.48]]


In [76]:
res

[0.9410737292017344,
 -0.45285249051070486,
 1.1000052046780466,
 -0.38301968435361805]

In [77]:
#matrix=np.delete(matrix, matrix.shape[0], 0)
np.round(matrix,3)

array([[10.39 ,  2.45 ,  3.35 ,  2.28 , 11.48 ],
       [ 0.   ,  6.028, -0.732, -0.125, -3.487],
       [ 0.   , -0.   ,  4.95 ,  0.013,  5.441],
       [ 0.   ,  0.   ,  0.   ,  0.901, -0.345],
       [ 0.   ,  1.   ,  2.   ,  3.   ,  4.   ]])

In [78]:
k = np.delete(matrix,matrix.shape[0]-1,0 )

In [79]:
np.round(k,3)

array([[10.39 ,  2.45 ,  3.35 ,  2.28 , 11.48 ],
       [ 0.   ,  6.028, -0.732, -0.125, -3.487],
       [ 0.   , -0.   ,  4.95 ,  0.013,  5.441],
       [ 0.   ,  0.   ,  0.   ,  0.901, -0.345]])

In [80]:
h = k[:,k.shape[1] -1]

In [81]:
k = np.delete(k, k.shape[1]-1, 1)

In [82]:
np.round(k,3)

array([[10.39 ,  2.45 ,  3.35 ,  2.28 ],
       [ 0.   ,  6.028, -0.732, -0.125],
       [ 0.   , -0.   ,  4.95 ,  0.013],
       [ 0.   ,  0.   ,  0.   ,  0.901]])