In [4]:
import numpy as np

In [5]:
A = np.array([[6.59,   1.28,   0.79,  1.195, -0.21  ], 
              [0.92,   3.83,    1.3,  -1.63,  1.02  ],
              [1.15,  -2.46,   5.77,    2.1,  1.483 ],
              [1.285,  0.16,    2.1,   5.77,  -18   ],
              [0.69,  -1.68, -1.217,      9,   -6   ]  ], dtype = float)

In [6]:
A

array([[  6.59 ,   1.28 ,   0.79 ,   1.195,  -0.21 ],
       [  0.92 ,   3.83 ,   1.3  ,  -1.63 ,   1.02 ],
       [  1.15 ,  -2.46 ,   5.77 ,   2.1  ,   1.483],
       [  1.285,   0.16 ,   2.1  ,   5.77 , -18.   ],
       [  0.69 ,  -1.68 ,  -1.217,   9.   ,  -6.   ]])

In [7]:
B = np.array([2.1, 0.36, 3.89, 11.04, -0.27])

In [8]:
B

array([ 2.1 ,  0.36,  3.89, 11.04, -0.27])

In [209]:
x = np.linalg.solve(A, B)

In [210]:
x

array([ 0.32954436, -0.26882477,  0.80811347, -0.41729254, -0.63168262])

__Шило М. ФІ - 61, Варіант 10__

### Метод Гауса

In [211]:
def ind(matr,el):                                      # функція ind показує розміщення елемента 'el' в м-ці 'matr'
    a = np.where(matr == el)
    r = [a[0][0].tolist(),a[1][0].tolist()]
    return r

In [212]:
def gauss_method(a,b):
    n = a.shape[1]
    global rest
    rest = [0]*n
    
    while n >0:
        print(a.shape)                                   # матриця А має розмірність
        a_main = abs(a).max()                            # знаходимо найбільший елемент м-ці А
        if a_main in a:
            a_main = a_main
        else:
            a_main = -a_main
        p = ind(a,a_main)[0]                             # головний рядок
        q = ind(a,a_main)[1]                             # головний стовпець
        m = []                                           # множники m_i
        for i in range(0, len(a[:,q])):
            if i!=p:
                m.append(a[:, q][i]/a[p,q])
            else:
                m.append(0)
        print(" ")        
        print("Множники m[i]: ",m )
        print(" ")
    
        rest.insert(n,a[p,:].tolist())                  #зберігаємо головний рядок  'p'
        rest[n].append(b[p])                            #зберігаємо елемент b[p]
        for i in range(0,a.shape[0] ):
            for j in range(0, a.shape[1]):
                a[i][j] = a[i][j] - m[i]*a[p][j]       #головний алгоритм
                b[i] = b[i] - m[i]*a[p][j]
        print(np.round(a,2),np.round(b,2) )            # показ з округленням 2ох цифр
        a = np.delete(a, q, 1)                         # видалення
        a = np.delete(a, p, 0)
        b = np.delete(b, p, 0)
        print(a.shape)
        n = n-1
    else:
        print(rest)

In [213]:
print("Початкова матриця")
print(np.round(A,4))
gauss_method(A,B)

Початкова матриця
[[  6.59    1.28    0.79    1.195  -0.21 ]
 [  0.92    3.83    1.3    -1.63    1.02 ]
 [  1.15   -2.46    5.77    2.1     1.483]
 [  1.285   0.16    2.1     5.77  -18.   ]
 [  0.69   -1.68   -1.217   9.     -6.   ]]
(5, 5)
 
Множники m[i]:  [0.011666666666666665, -0.05666666666666667, -0.0823888888888889, 0, 0.3333333333333333]
 
[[  6.58   1.28   0.77   1.13  -0.  ]
 [  0.99   3.84   1.42  -1.3    0.  ]
 [  1.26  -2.45   5.94   2.58   0.  ]
 [  1.28   0.16   2.1    5.77 -18.  ]
 [  0.26  -1.73  -1.92   7.08   0.  ]] [ 2.2  -0.13  3.17 11.04  2.62]
(4, 4)
(4, 4)
 
Множники m[i]:  [0.15935233160621762, -0.1841309467734338, 0.3639261265504789, 0]
 
[[ 6.53  1.55  1.07  0.  ]
 [ 1.04  3.52  1.07  0.  ]
 [ 1.16 -1.82  6.64  0.  ]
 [ 0.26 -1.73 -1.92  7.08]] [1.61 0.55 1.83 2.62]
(3, 3)
(3, 3)
 
Множники m[i]:  [0.16127582613686103, 0.16052929757254122, 0]
 
[[ 6.35  1.85  0.  ]
 [ 0.85  3.81  0.  ]
 [ 1.16 -1.82  6.64]] [ 0.65 -0.41  1.83]
(2, 2)
(2, 2)
 
Множники m[i]:  

In [186]:
rest

[0,
 [3.5626502298727956, -1.5173497701272047],
 0,
 [6.3461275802810775, 1.8472229563337383, 0.6483505366148152],
 0,
 [1.160642385774847,
  -1.8160124917569473,
  6.6406630512639335,
  1.832292945281833],
 0,
 [0.26166666666666666, -1.7333333333333332, -1.917, 7.076666666666667, 2.625],
 0,
 [1.285, 0.16, 2.1, 5.77, -18.0, 11.04]]

In [187]:
t = []
for i in range(0,len(rest)):
    if i%2 != 0:
        t.append(rest[i])

In [188]:
for i in range(0,len(t)):
    t[i] = [ round(elem, 2) for elem in t[i] ]

In [189]:
t.reverse()

In [190]:
t   # тіпа розв'язок

[[1.28, 0.16, 2.1, 5.77, -18.0, 11.04],
 [0.26, -1.73, -1.92, 7.08, 2.62],
 [1.16, -1.82, 6.64, 1.83],
 [6.35, 1.85, 0.65],
 [3.56, -1.52]]

In [9]:
A[:,0]

array([6.59 , 0.92 , 1.15 , 1.285, 0.69 ])

In [ ]:
[[  6.58   1.28   0.77   1.13  -0.  ]
 [  0.99   3.84   1.42  -1.3    0.  ]
 [  1.26  -2.45   5.94   2.58   0.  ]
 [  1.28   0.16   2.1    5.77 -18.  ]
 [  0.26  -1.73  -1.92   7.08   0.  ]]