In [1]:
import numpy as np

In [2]:
A = np.array([[2.2,   1, 0.5,    2],
              [1  , 1.3,   2,    1],
              [0.5,   2, 0.5,  1.6],
              [  2,   1, 1.6,   2]], dtype = float)

In [3]:
w, v = np.linalg.eig(A)
print(w)
print()
print(v)

[ 5.65203233  1.54541834  0.22263593 -1.42008659]

[[ 0.53173607  0.62892976  0.52192057  0.22204284]
 [ 0.44619412 -0.57257423  0.45486932 -0.51591032]
 [ 0.40881553 -0.4856538  -0.15344702  0.75727423]
 [ 0.59248411  0.20185762 -0.7050864  -0.33327054]]


In [4]:
delta = [[9,11],[6.7,8],[4.1,6],[1,4]]

In [5]:

def Danilevskyi_method(A):
    K= np.eye(4)
    for k in range(0,A.shape[0] -1):
        B = np.eye(A.shape[0])
        for i in range(0,len( B[B.shape[0] - 2])):
            if i == A.shape[1]-(2+k):
                B[B.shape[0] - (2+k),i] = 1/A[A.shape[0]-(1+k), A.shape[1]-(2+k)]
            else:
                B[B.shape[0] - (2+k),i] = - A[A.shape[0]-(1+k),i]/A[A.shape[0]-(1+k), A.shape[1]-(2+k)]
        B_1 = np.linalg.inv(B)
        D = np.round(B_1.dot(A).dot(B),2)
        K = np.concatenate((K,B),0)
        A = D
    return A

In [6]:
Danilevskyi_method(A)

array([[  6.01,   0.14, -12.74,   2.78],
       [  1.  ,   0.  ,   0.  ,   0.  ],
       [  0.  ,   1.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   1.  ,   0.  ]])

In [62]:
K

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
coef = -Danilevskyi_method(A)[0,]
coef

array([-6.01, -0.14, 12.74, -2.78])

In [32]:
coef=np.concatenate((np.array([pow(1,A.shape[0])]), coef), axis=None)
np.round(np.roots(coef),2)

array([ 5.65, -1.42,  1.55,  0.22])

In [25]:
coef

array([ 1.  , -6.01, -0.14, 12.74, -2.78])

In [26]:
def f(t):
    f = 0
    for i in range(0,len(coef)):
        f = f + coef[i]*pow(t,len(coef) -i -1)
    return f

In [15]:
e = 0.0000001
def method_of_chords(a,b):
    k=0
    while abs(a- (a - (f(a)*(a-b))/(f(a)-f(b)))   ) > e:
        k = k + 1
        a = a - (f(a)*(a-b))/(f(a)-f(b))
        b = b
    return a


In [16]:
own_numbers = []
for i in delta:
    own_numbers.append(method_of_chords(i[0],i[1]))

In [17]:
own_numbers

[10.406723910900103, 7.326519373447115, 5.68211043843639, 3.3846461896125337]

In [40]:
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])
np.concatenate((a,b),0)

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
B1= np.array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [-1.25      , -0.625     ,  0.625     , -1.25      ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [64]:
B2 = np.array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [-0.35194175,  0.24271845, -1.0631068 , -0.68203883],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [65]:
B3 = np.array([ [-0.23201856,  1.08352668,  1.65429234, -1.16009281],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [94]:
B = np.round(B3.dot(B2).dot(B1),2)

In [95]:
B

array([[-1.24, -0.05,  0.31, -2.53],
       [ 0.98,  0.91, -0.66,  0.65],
       [-1.25, -0.62,  0.62, -1.25],
       [ 0.  ,  0.  ,  0.  ,  1.  ]])

In [96]:
y1 = np.array([w[0]**3,w[0]**2,w[0]**1, w[0]**0])
y2 = np.array([w[1]**3,w[1]**2,w[1]**1, w[1]**0])
y3 = np.array([w[2]**3,w[2]**2,w[2]**1, w[2]**0])
y4 = np.array([w[3]**3,w[3]**2,w[3]**1, w[3]**0])

In [97]:
x1 = B.dot(y1)
x2 = B.dot(y2)
x3 = B.dot(y3)
x4 = B.dot(y4)

In [98]:
print(x1)
print(x2)
print(x3)
print(x4)

[-226.26560813  202.93572571 -243.24796397    1.        ]
[-6.74711441  5.42052429 -6.38628539  1.        ]
[-2.47714502  0.55898067 -1.15649129  1.        ]
[0.48006756 0.61586933 0.19899065 1.        ]


In [99]:
for i in range(0,4):
    print(x1[i]/np.linalg.norm(x1))

-0.5812207909368504
0.5212920513371706
-0.6248442933210882
0.00256875446406308


In [100]:
for i in range(0,4):
    print(x2[i]/np.linalg.norm(x1))

-0.017331680265724545
0.013923995957398107
-0.016404799112570548
0.00256875446406308


In [101]:
for i in range(0,4):
    print(x3[i]/np.linalg.norm(x1))

-0.0063631773355641115
0.0014358840913170454
-0.0029707421632959286
0.00256875446406308


In [102]:
for i in range(0,4):
    print(x4[i]/np.linalg.norm(x1))

0.0012331756895657983
0.0015820170991632217
0.0005111581270736246
0.00256875446406308
